# Generated by Django 2.2.12 on 2020-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='is_direct',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dos',
            name='is_directBG',
            field=models.BooleanField(null=True),
        ),
    ]
